version = 1
SPDX-PackageName = "weavejs"
SPDX-PackageSupplier = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/weavejs"

[[annotations]]
path = [
    # root level licensing
    ".github/**",
    "images/**",
    "REUSE.toml",
    "repolinter.json",

    # repeated files licensing
    "**/.gitignore",
    "**/tsconfig.json",
    "**/package*.json",
    "**/.eslintrc",

    # code/ directory licensing
    "code/packages/create-backend-app/**",
    "code/packages/create-frontend-app/**",
    "code/packages/store-azure-web-pubsub/docker-compose.yml",
    "code/packages/store-azure-web-pubsub/DockerfileExpressBackend",
    "code/packages/store-azure-web-pubsub/DockerfileKoaBackend",
    "code/packages/store-azure-web-pubsub/DockerfileNginx",
    "code/packages/store-azure-web-pubsub/nginx.conf",
    "code/packages/store-websockets/docker-compose.yml",
    "code/packages/store-websockets/DockerfileExpressBackend",
    "code/packages/store-websockets/DockerfileKoaBackend",
    "code/packages/store-websockets/DockerfileNginx",
    "code/packages/store-websockets/nginx.conf",
    "code/.husky/**",
    "code/verdaccio/**",
    "code/.eslintignore",
    "code/.prettierignore",
    "code/.prettierrc",
    "code/.tool-versions",
    "code/lerna.json",
    "code/nx.json",
    "code/tsconfig.base.json",

    # docs/ directory licensing
    "docs/**",
    "docs-old/**",

    # code/patches/ directory licensing
    "code/patches/**"
]
SPDX-FileCopyrightText = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
