site:
  title: Weave.js
  start_page: weavejs::index.adoc
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: docs/src
      edit_url: "{web_url}/edit/develop/{path}"
      version:
        (*): prerelease
asciidoc:
  attributes:
    experimental: ""
    source-highlighter: ~
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
